### ISSUE TITLE
Hodnocení úkolu #2

### ISSUE THREAD

**Issue by tommander** [JitkaHo/PROJEKT-Vizitka#1]
<p>Moc pěkně udělané, všechno funguje, jak má, hezky vycentrované, super :) Poprosím o jedinou věc &mdash; opravit mezery mezi odstavci dle zadání a bude to <em>perfektní</em> :)</p>

**Comment by JitkaHo** [comment]
@tommander , děkuju, no asi neumím číst, tak teď by to mělo být :)

**Comment by tommander** [comment]
<p>&hellip; no a je to perfektní :) Děkuju, dobrá práce 👍 </p>
